import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import type { Props } from '@/types';
import { panda } from '@panda/jsx';

const inter = Inter({
  subsets: ['latin-ext'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Root = (props: Props) => {
  const { children } = props;

  return (
    <panda.html lang='en' className={inter.variable}>
      <body>
        <panda.main>{children}</panda.main>
      </body>
    </panda.html>
  );
};

export default Root;
